column_use:
  - phase
  - measurement
  - low_limit
  - high_limit
version: Version 2.0 - Enzo 2026
ftp_host: 10.239.73.213
ftp_user: Images
ftp_password: DMSTE@SFTP189
ftp_port: 22
ftp_remote: /.Enzo/
size: 1800x1000





  